apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.backend.name }}
  name: {{ .Values.backend.name }}
  namespace: default
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
      - image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        name: {{ .Values.backend.name }}
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
        ports:
          - name: {{ .Values.backend.name }}-port
            containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.frontend.name }}
  name: {{ .Values.frontend.name }}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
      - image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        name: {{ .Values.frontend.name }}
        livenessProbe:
          httpGet:
            path: /api/healthcheck
            port: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        env:
        - name: API_BASE_URL
          value: {{ .Values.frontend.API_BASE_URL }}


