apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: {{ .Values.backend.name }}-port
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  type: LoadBalancer